PROFILE_NAME={{PROFILE_NAME}}
VM_HOST={{VM_HOST}}
INSTANCE_ID={{INSTANCE_ID}}
CHECK_INTERVAL={{CHECK_INTERVAL}}
PING_ATTEMPTS={{PING_ATTEMPTS}}
PING_TIMEOUT={{PING_TIMEOUT}}
SA_KEY_FILE={{SA_KEY_FILE}}
